# Generated by Django 4.0.2 on 2022-02-17 14:27

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeIn', models.TimeField(auto_now=True)),
                ('timeOut', models.TimeField(auto_now=True)),
                ('vacationTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacationUsed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacationInput', models.BooleanField(default=False)),
                ('sickTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sickUsed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sickInput', models.BooleanField(default=False)),
                ('yearsExperience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='createAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('DOB', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Female')], max_length=6)),
                ('startDate', models.DateField(max_length=8)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=255)),
                ('empAddress', models.CharField(max_length=255)),
                ('empCity', models.CharField(max_length=255)),
                ('empZip', models.IntegerField()),
                ('empPhone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
