# Generated by Django 4.0.2 on 2022-02-23 18:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ourAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empFirst', models.CharField(max_length=255)),
                ('empMiddle', models.CharField(max_length=255)),
                ('empLast', models.CharField(max_length=255)),
                ('empAddress', models.CharField(max_length=255)),
                ('empCity', models.CharField(max_length=255)),
                ('empState', models.CharField(max_length=255)),
                ('empZip', models.IntegerField()),
                ('empPhone', models.IntegerField(blank=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='createAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Female')], max_length=6)),
                ('startDate', models.DateField(max_length=8)),
                ('idNumber', models.IntegerField()),
                ('vacationTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sickTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
